name: Sync Repository

on:
  schedule:
    - cron: '0 * * * *' # Runs every hour
  workflow_dispatch: # Allows manual trigger

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Target Repository
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Add Source Repository and Sync
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          
          # Add source repository (ignore if already added)
          git remote | grep source || git remote add source https://github.com/praveensaneforceofficial/sivanyaapi.git
          
          # Fetch latest changes from source
          git fetch source

          # Checkout main branch
          git checkout main
          
          # Merge source/main into target/main with conflict handling
          git merge source/main --allow-unrelated-histories -m "Auto-sync from praveensaneforceofficial/sivanyaapi" || (
            echo "Merge conflict detected. Resolving by keeping source changes."
            git checkout --theirs .
            git add .
            git commit -m "Resolved merge conflict by keeping source changes"
          )

          # Push changes to target repo (praveensri2018/sivanyaAPI)
          git push origin main
